{
  "name": "AvoidCatchingNPE",
  "language": "java",
  "description": "\nCode should never throw NullPointerExceptions under normal circumstances.  A catch block may hide the\noriginal error, causing other, more subtle problems later on.\n        ",
  "example": "public class Foo {\n    void bar() {\n        try {\n            // do something\n        } catch (NullPointerException npe) {\n        }\n    }\n}",
  "cwe": null,
  "cwe-description": null,
  "checker-language": "java",
  "loc": 0,
  "branches": 0,
  "apis": 0,
  "test": [
    {
      "description": "failure case",
      "expected-problems": 1,
      "expected-linenumbers": [
        4
      ],
      "code": "\npublic class Foo {\n    void bar() {\n        try {\n        } catch (NullPointerException e) {\n        }\n    }\n}\n        "
    },
    {
      "description": "catching another type, ok",
      "expected-problems": 0,
      "expected-linenumbers": [],
      "code": "\npublic class Foo {\n    void bar() {\n        try {\n        } catch (FooException e) {\n        }\n    }\n    public static class FooException extends NullPointerException {}\n}\n        "
    },
    {
      "description": "throwing it, ok",
      "expected-problems": 0,
      "expected-linenumbers": [],
      "code": "\npublic class Foo {\n    void bar() {\n        throw new NullPointerException();\n    }\n}\n        "
    }
  ]
}