{
  "name": "CatchingUnchecked",
  "language": "java",
  "description": "This catch block catches `Exception`, but can only catch unchecked exceptions. Consider catching RuntimeException (or something more specific) instead so it is more apparent that no checked exceptions are being handled.",
  "example": null,
  "cwe": null,
  "cwe-description": null,
  "checker-language": "java",
  "loc": 76,
  "branches": 8,
  "apis": 3,
  "test": [
    {
      "description": "positive",
      "expected-problems": null,
      "expected-linenumbers": [
        30
      ],
      "code": "class Test {\n              void test() {\n                try {\n                  this.hashCode();\n                  // BUG: Diagnostic contains:\n                } catch (Exception e) {\n                }\n              }\n            }"
    },
    {
      "description": "positiveMultiCatch",
      "expected-problems": null,
      "expected-linenumbers": [
        49
      ],
      "code": "import java.io.IOException;\n\n            class Test {\n              void test() {\n                try {\n                  throw new IOException();\n                } catch (IOException e) {\n                  // BUG: Diagnostic contains:\n                } catch (Exception e) {\n                }\n              }\n            }"
    },
    {
      "description": "negative",
      "expected-problems": null,
      "expected-linenumbers": [
        71
      ],
      "code": "class Test {\n              void test() {\n                try {\n                  throw new Exception();\n                } catch (Exception e) {\n                }\n              }\n            }"
    }
  ]
}