{
  "name": "Wrong name for an argument in a call",
  "description": "Using a named argument whose name does not correspond to a",
  "cwe": "quality",
  "cwe-description": null,
  "language": "python",
  "checker-language": "ql",
  "example": null,
  "loc": 11,
  "test": [],
  "branches": 1,
  "apis": 8
}